version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: deps
    environment:
      NODE_ENV: development
      PORT: 8000
    working_dir: /app/backend
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    ports:
      - "8000:8000"

  web:
    build:
      context: .
      dockerfile: web-app/Dockerfile
      target: deps
    environment:
      NODE_ENV: development
      PORT: 3000
    working_dir: /app/web-app
    volumes:
      - .:/app
      - /app/node_modules
      - /app/web-app/.next
    command: npm run dev
    ports:
      - "3000:3000"

  admin-dashboard:
    build:
      context: .
      dockerfile: admin-dashboard/Dockerfile
      target: deps
    environment:
      NODE_ENV: development
      PORT: 3001
    working_dir: /app/admin-dashboard
    volumes:
      - .:/app
      - /app/node_modules
      - /app/admin-dashboard/.next
    command: npm run dev
    ports:
      - "3001:3001"
